spring.application.name=springboot

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=deepanshu
spring.datasource.password=deepanshu
spring.h2.console.enabled=true

application.user.name=Deepanshu
application.user.age=21

management.endpoints.web.exposure.include=*

